public class javaBasic{
    public static void main(String arg[]){
        System.out.println("Hello World");
        System.out.println("rakesh");
        System.out.print("rakesh\nvishwakarma");
    }
}
// .class file is a byte code which generated by after compliation process. 
// source code(.java) --> compiler --> byte code(.class)--> JVM --> Native code(low level language)
// print and println is Function in java
// println in ln is use for line space and also we can use \n for line space.

//Comment in java by single line we use // and for multiple line we use a /* comments */
